### ISSUE TITLE
Support for chatList options

### ISSUE THREAD

**Issue by nathunsmitty** [keybase/keybase-bot#23]

**Comment by thebearjew** [comment]
This is done actually? Options are passed in to chat list right now.

**Comment by thebearjew** [comment]
Closed by #13

**Comment by nathunsmitty** [comment]
schweet

**Comment by thebearjew** [comment]
The current `chatList` supports all the existing options via `keybase chat api` which are only:
https://github.com/keybase/client/blob/master/go/client/chat_api_handler.go#L123-L128

Remaining options that need to be added by CORE

- [ ] num
- [ ] time / since
- [ ] include hidden
- [ ] channel
- [ ] public
- [ ] private

**Comment by nathunsmitty** [comment]
think the bot types project has satisfied this
